language: java
jdk:
  - oraclejdk8
 
env:
  - TEST_DIR=EscapeServer
  - TEST_DIR=EscapeVR

script: cd $TEST_DIR && mvn test -B && mvn site

after_script:
  - echo "== Speciaal voor Jurgeb en Sander =="
  - echo "== CHECKSTYLE_RESULT =="; cat "target/checkstyle-result.xml"; echo "== END_CHECKSTYLE_RESULT =="
  - echo "== PMD_RESULT =="; cat "target/pmd.xml"; echo "== END_PMD_RESULT =="
  - echo "== FINDBUGS_RESULT =="; cat "target/findbugsXml.xml"; echo "== END_FINDBUGS_RESULT =="
